project:
  type: website

website:
  title: "Git_pour_Stat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: liste.qmd
        text: idées listes
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



